### ISSUE TITLE
Future Goals roadmap

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#435]
Major enchants:
- [ ] UPDATE SKINSGUI MEGA THREAD #363 (resolved a lot of related issues)
  - [ ] Cache
- [x] improved SkinsRestorer API with more features & switches (Yet to be decided)
- [x] Backend api
  - [ ] pluginmessagechannel??? --> maybe better solution 
- [ ] Rework Skinstorage
  - [x] Storage pools
  - [ ] use json flatfile
  - [ ] cooldown storage
- [x] translations

Other enchants:
- [ ] add cache for getSkinsRaw & getSkins for bighost #303
- [ ] Pleayerheads #180
- [ ] Converter [mysql&flatfile] #848 
- [x] Purger for old skin data #914
- [ ] hex color

optional enchants:
- [ ] add mineskin & github to status #313
- [ ] [REQUEST] Cancel message when blank message #261

**Comment by xknat** [comment]
created new issue from not already committed / issued feature's listed above
